nlu:
- intent: AnnualLeaveApplicationProcess
  examples: '- How about annual leave?

    - annual leave?

    - annual leave process

    - How about annual leave process

    - How about annual leave application process

    '
