actions_map:
- intent: default
  priority: 0
  triggers:
  - action: default
- intent: restart
  triggers:
  - action: restart
- intent: SetWorkingType
  set_slot:
    working_type:
      from_entity:
        working_type: true
        shift_type: shift
  triggers:
  - slot:
      working_type: true
    trigger_intent:
      from_slot: latest_question
  - text:
    - Ok I will remember your working type
- intent: greet
  priority: 0
  triggers:
  - slot:
      start_session: true
    text:
    - converasion started
  - set_slot:
      start_session: start
    text:
    - hi __user__
- intent: goodbye
  triggers:
  - text:
    - bye
- intent: WorkTimesBreaches
  set:
    latest_question: WorkTimesBreaches
  set_slot:
    working_type:
      from_entity:
        working_type: true
        shift_type: shift
  triggers:
  - slot:
      working_type: office hours
    text:
    - '**Late-in** means check-in time is within 90 mins after start time in the morning;
      or after start time in the afternoon in case of half-day off in the morning

      **Early-out** means check-out time is within 90 mins before finish time in the
      afternoon; or before finish time in the morning in case of half-day off in the
      afternoon

      **Late-in/Early-out** is considered half-day off if the _Late-in check-in time_
      or _Early-out check-out time_ exceed the regulated mentioned number of minutes

      '
  - slot:
      working_type: shift
    text:
    - '**Late-in** means check-in time is within 30 mins after start time of the first
      half-shift; or after the start time of the second half-shift in case of first
      half-shift off

      **Early-out** means check-out time is within 30 mins before finish time of the
      second half-shift; or before the finish time of the fisrt half-shift in case
      of second half-shift off

      **Late-in/Early-out** is considered half-shift off if the _Late-in check-in
      time_ or _Early-out check-out time_ exceed the regulated mentioned number of
      minutes

      '
  - request_slot: working_type
- intent: WorkingHours
  set:
    latest_question: WorkingHours
  set_slot:
    working_type:
      from_entity:
        working_type: true
        shift_type: shift
  triggers:
  - slot:
      working_type: office hours
    text:
    - 'Employee will work from 8:30 to 17:30 in a day (Mon - Fri).

      '
  - slot:
      working_type: shift
      shift_type: day shift
    text:
    - "**DAY SHIFT (SHIFT 1)**\nShift 1A: (06h00 - 14h00)\n  - _(Work shift with 08\
      \ consecutive hours/day, 30 mins break included in working hours)_\nShift 1B:\
      \ (07h00 - 14h00)\n  - _(Work shift with 07 consecutive hours/day, 30 mins break\
      \ included in working hours)_\nShift 1C: (07h00 - 16h00)\n  - _(Work shift with\
      \ 08 working hours/day, rotary 01-hour break among employees from [11h00 - 12h00]\
      \ or [12h00 - 13h00] excluded from working hours)_\n"
  - slot:
      working_type: shift
      shift_type: afternoon shift
    text:
    - "**AFTERNOON SHIFT (SHIFT 2)**\nShift 2A: (14h00 - 22h00)\n  - _(Work shift\
      \ with 8 consecutive hours/day, 30 mins break included in working hours)_\n\
      Shift 2B: (14h00 - 21h00)\n  - _(Work shift with 7 consecutive hours/day, 30\
      \ mins break included in working hours)_\nShift 2C: (12h00 - 21h00)\n  - _(Work\
      \ shift with 08 working hours/day, rotary 01-hour break among employees from\
      \ [16h30 - 17h30] or [17h30 - 18h30] excluded from working hours)_\n"
  - slot:
      working_type: shift
      shift_type: night shift
    text:
    - "**NIGHT SHIFT (SHIFT 3)**\nShift 3A: (Night shift) (22h00 - 06h00)\n  - _(Work\
      \ shift with 8 consecutive hours/day, 45 mins break included in working hours)_\n"
  - slot:
      working_type: shift
    request_slot: shift_type
  - request_slot: working_type
- intent: WorkingDay
  set:
    latest_question: WorkingDay
  set_slot:
    working_type:
      from_entity:
        working_type: true
        shift_type: shift
  triggers:
  - slot:
      working_type: office hours
    text:
    - 'You must work 5 days a week, from Monday to Friday

      '
  - slot:
      working_type: shift
    text:
    - 'Based on your allocated work shifts each month

      '
  - request_slot: working_type
- intent: WorkingTimeBreachDiscipline
  set:
    latest_question: WorkingTimeBreachDiscipline
  triggers:
  - text:
    - "The allowable frequency for both _Late-in_ and _Early-out_ is 2 times per month.\
      \ Every 03 breaches in a month will be deducted 1/2 day from annual leave\n\
      \  - Employee must guarantee the total remaining work time of each half-day/shift\
      \ not less than 02 hours if _Late-in/Early-out_ in case of half-day work. Each\
      \ breach will be deducted 1/2 day from annual leave\n  - _Late-in/Early-out_\
      \ is considered half-day/half-shift off if the _Late-in check-in time_ or _Early-out\
      \ check-out time_ exceed the regulated mentioned number of minutes. Therefore,\
      \ 1/2 day of annual leave will be deducted for each case\n  - _Late-in_ and\
      \ _Early-out_ happen in a day is counted as 02 breaches\n  - In case of many\
      \ breaches incurred in the same half-day, if annual leave deduction is applied\
      \ for one breach, the other ones will not be counted. Maximum 0.5 day of annual\
      \ leave will be deducted for this half-day\n"
- intent: HolidaysOff
  set:
    latest_question: HolidaysOff
  triggers:
  - text:
    - "1. Calendar New Year Holiday: 01 day (Lunar calendar, 01st Jan);\n2. Lunar\
      \ New Year Holidays: 05 days (Lunar calendar, following Government's schedule)\n\
      3. Reunification Day: 01 day (30th Apr)\n4. International Labor Day: 01 day\
      \ (01st May)\n5. National Day: 01 day (02nd Sep + 01 day before/ after holiday\
      \ following Government's schedule (*)\n6. Hung King Anniversary: 01 day (Lunar\
      \ calendar, 10th Mar)\n(*) Effective from 01 Jan 2021\n(*) For employees working\
      \ on office-hours\n  Employee who works on office hours are entitled to the\
      \ paid days off on holidays\n(*) For employees working on shifts\n  Employees\
      \ on shifts are required working on work shift as normal on holidays according\
      \ to team lead's arrangement\n  Employees on shift who are in probation period\
      \ are entitled to the paid days off on holidays. However, employees have to\
      \ work on these days if required\n"
- intent: AnnualLeaveApplicationProcess
  set:
    latest_question: AnnualLeaveApplicationProcess
  triggers:
  - text:
    - "Employees are required to follow the application procedure for annual leave\
      \ as below:\n  1 - Apply leave request for annual leave via internal system\
      \ of the company (Blueprint), which must be approved by 02 approval levels before\
      \ taking day-off\n  2 - In case of short-term leave (from 1 to 2 working days),\
      \ employees need to apply leave request at least 01 working-day in advance\n\
      \  3 - In case of long-term leave (more than 2 working days), employees need\
      \ to apply leave request at least 05 working-day in advance\n  4 - In case of\
      \ force majeure, employees need to notify project leader and register _leave\
      \ request_ on the first day back to work\n  (*) The valid approved annual leave\
      \ following the mentioned procedure is paid leave\nBased on the consideration\
      \ of specific situation, invalid day-off is treated as unpaid leave; therefore,\
      \ annual leave will not be deducted in this case\n"
- intent: BreakTime
  set:
    latest_question: BreakTime
  set_slot:
    working_type:
      from_entity:
        working_type: true
        shift_type: shift
  triggers:
  - slot:
      working_type: office hours
    text:
    - 'Lunch time from 12:00 to 13:00 every working days

      '
  - slot:
      working_type: shift
    text:
    - 'You have 30 mins break included in the working hours

      '
  - request_slot: working_type
- intent: Pregnant
  set:
    latest_question: Pregnant
  set_slot:
    working_type:
      from_entity:
        working_type: true
        shift_type: shift
  triggers:
  - slot:
      working_type: office hours
    text:
    - 'General employee - Female employees who are pregnant from 7th month or have
      children under one year old can work 7 hours/day, per 5 days/week from 8:30
      to 16:30.

      '
  - slot:
      working_type: shift
    text:
    - 'Pregnant employees that work on shift will be arranged according to the situation.

      '
  - request_slot: working_type
- intent: AttendanceRecord
  set:
    latest_question: AttendanceRecord
  triggers:
  - text:
    - All employees are required to daily check in/out when coming or leaving the
      office. Attendance data is recorded and followed up by the company management
      system (Blueprint)
- intent: LaborContract
  set:
    latest_question: LaborContract
  triggers:
  - text:
    - 'Those employees who pass the probation period can sign the official labor contract
      following orders below:

      Time 01: Definite labor contract (12 months)

      Time 02: Continue with indefinite labor contract; however, in case of necessity,
      the Company can consider for another 12-month definite labor contract before
      the indefinite labor contract depending on particular situation

      For employee as other citizen working in Vietnam. The two Parties agree to sign
      many definite-term labor contracts provided that the term of the labor contract
      does not exceed the term of the work permit

      '
- intent: Recruitment
  set:
    latest_question: Recruitment
  triggers:
  - text:
    - "(*) Employees working at the Company have to follow through the recruitment\
      \ process; and the approval result shall be based on individual capability,\
      \ professional major and experience specifically required for each particular\
      \ job title / position\n(*) Employees are required to submit personal documents\
      \ upon working at the company, items included:\n  - Resume / CV\n  - Personal\
      \ profile (notorized)\n  - Copied resident book and ID card (notorized)\n  -\
      \ Copied transcript and qualifications (if any)\n  - 3x4 picture (2 pieces)\n"
- intent: SickLeave
  set:
    latest_question: SickLeave
  triggers:
  - text:
    - '(*) In case of sudden leave of absence for sickness or risk of accident, employee
      or employee'' family (understood as Father / Mother / Husband / Wife / Sibling)
      must inform HR department or line manager at the earliest. After the sick leave
      period, employee has to submit sick leave request with Certificates of Paid
      Leaves covered by the Social Insurance scheme (C65-HD) signed and stamped by
      doctor

      (*) Sick leave is counted as unpaid leave. During the sick leave period following
      doctor''s description/instruction, contracted employee shall be covered by the
      policy of Social Insurance

      '
- intent: UnpaidLeave
  set:
    latest_question: UnpaidLeave
  triggers:
  - text:
    - '(*) Employee can ONLY apply for maximum 05 unpaid days of leave per year if
      all of issued annual leave has been used up in the year. The application has
      to be approved by all approval levels

      (*) If the number of applied unpaid days of leave exceeds the mentioned limit
      above, employee has to clearly explain the reason to HR department and present
      all the related documents (upon request) to be used as proof for consideration
      and approval

      '
- intent: PaidLeaveForFamilyEvent
  set:
    latest_question: PaidLeaveForFamilyEvent
  triggers:
  - text:
    - '1 - Marriage: 03 days off

      2 - Son/daughter''s marriage: 01 day off

      3 - Death of parents (including parents in law), husband or wife or children
      03 days off

      4 - Death of grandparents: 01 day off

      '
- intent: UnusedAnnualLeave
  set:
    latest_question: UnusedAnnualLeave
  triggers:
  - text:
    - '(*) The number of unused annual leave of year shall be carried forward to use
      until 31st Dec of next year

      (*) However, employees, who work on shift and don''t use up all annual leave
      in a year due to job nature and requirement, shall be paid for unused annual
      leave. The paid amount is 100% of current salary and settled with salary transfer
      in Dec of the year

      '
- intent: RegulatedAnnualLeave
  set:
    latest_question: RegulatedAnnualLeave
  triggers:
  - text:
    - "Regulated annual leave of the year for each type of employee:\n  [1] Employee\
      \ as Vietnamese citizen: 12 days\n  [2] Employee as Korean citizen: 12 days\n\
      \  [3] Employee as other country citizen: 18 days\n    - Annual leave can be\
      \ used after signing labor contract\n    - 01 extra annual leave for every 03\
      \ years working consecutively at the company counted from the start date\n"
requests_map:
- slot: working_type
  set_slot:
    working_type:
      from_entity:
        working_type: true
        shift_type: shift
  button:
    text: What is your working type?
    button:
    - title: office hours
      synonym:
      - office
      set_slot:
        working_type: office hours
    - title: shift
      set_slot:
        working_type: shift
  redirect:
  - slot:
      working_type: true
    set_slot:
      request_slot: null
    trigger_intent:
      from_slot: latest_question
  - intent:
      priority: 0
    button:
      text: What is your working type?
      button:
      - title: office hours
        synonym:
        - office
        set_slot:
          working_type: office hours
      - title: shift
        set_slot:
          working_type: shift
  - intent:
      priority: 1
    set_slot:
      request_slot: null
      confirm_request:
        from_intent: true
    request_slot: continue_confirmation
- slot: shift_type
  set_slot:
    shift_type:
      from_entity:
        shift_type: true
  button:
    text: What is your shift type?
    button:
    - title: day shift
      synonym:
      - day
      set_slot:
        shift_type: day shift
    - title: afternoon shift
      synonym:
      - afternoon
      set_slot:
        shift_type: afternoon shift
    - title: night shift
      synonym:
      - night
      set_slot:
        shift_type: night shift
  redirect:
  - slot:
      shift_type: true
    set_slot:
      request_slot: null
    trigger_intent:
      from_slot: latest_question
  - intent:
      priority: 0
    button:
      text: What is your shift type?
      button:
      - title: day shift
        synonym:
        - day
        set_slot:
          shift_type: day shift
      - title: afternoon shift
        synonym:
        - afternoon
        set_slot:
          shift_type: afternoon shift
      - title: night shift
        synonym:
        - night
        set_slot:
          shift_type: night shift
  - intent:
      priority: 1
    set_slot:
      request_slot: null
      confirm_request:
        from_intent: true
    request_slot: continue_confirmation
- slot: continue_confirmation
  text:
  - User did not answer my question, do you want to answer?
  redirect:
  - intent:
      name: affirm
    set_slot:
      request_slot: null
    trigger_intent:
      from_slot: latest_question
  - set_slot:
      request_slot: null
    trigger_intent:
      from_slot: confirm_request
